# Generated by Django 3.1.7 on 2021-05-31 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210526_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='account',
        ),
    ]
